### PR TITLE
Update EZGUI.js

### PR DESCRIPTION
**Pull request by llevkin**
UI crash if static server has other origin...

### CODE REVIEW

**Comment by alaa-eddine** [comment]
Good catch :)
this need to be added to souce TypeScript files .
I'll modify the corresponding sources.

maybe EZGUI need an initialization function or config namespace to pass such config settings

**Comment by alaa-eddine** [comment]
I'll merge this PR to remove it from pending PRs and push a new updates

**Comment by alaa-eddine** [comment]
Updated.
I added crossorigin settings to both Pixi and Phaser.

to set crossOrigin please use this syntax before any call to EZGUI.create or loading theme : 

```
EZGUI.settings.crossOrigin = true;
```

please use the latest dev version : https://github.com/Ezelia/EZGUI/blob/master/dist/EZGUI.js

Let me know if the new code work for you.

**Comment by llevkin** [comment]
Now all work fine! Thank's! I think you project is very good, but it's a "raw" and need to improve it... I found some issue, and I publish it with your permission.. This project - what I need now..

**Comment by alaa-eddine** [comment]
the project is still in early developement stage, so yes there may be many issues .
Feel free to report bugs or suggest PRs :)

**Pull request closed without merging**
